### ISSUE TITLE
There's no __init__.py in 'twisted/plugins/'

### ISSUE THREAD

**Issue by Cellularhacker** [sourcesimian/txTelegramBot#1]
This is the result after run '$sudo pip3 setup.py install'

/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'twisted/plugins/**init**.py' not found (or not a regular file)
package init file 'twisted/plugins/**init**.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /usr/local/lib/python3.4/dist-packages/txTelegramBot-0.2.egg-info
Writing /usr/local/lib/python3.4/dist-packages/txTelegramBot-0.2.egg-info

**Comment by sourcesimian** [comment]
Thanks, will take a look when I get a chance. However I've not seen your command line usage before. I suggest:
`$ pip3 install txTelegramBot`
or
`$ python3 ./setup.py install`

Also BTW, installing with `sudo` will write directly to your primary Python installation, it is better to make use of a [virtual env](https://docs.python.org/3/library/venv.html#module-venv).

Further, please note that this project has mostly been superseded by [aioTelegramBot](https://github.com/sourcesimian/aioTelegramBot) which is based on [asyncio](https://docs.python.org/3/library/asyncio.html) rather than [Twisted](https://twistedmatrix.com).
